# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=255)),
                ('arrivalDate', models.DateField()),
                ('estBirthDate', models.DateField()),
                ('description', models.CharField(max_length=400)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
