# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 10:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20160316_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='creationDate',
            field=models.DateField(default=datetime.datetime(2016, 3, 16, 10, 23, 52, 493947, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
