# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 10:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_profile_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='arrivalDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='profile',
            name='creationDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='profile',
            name='estBirthDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
